SET IDENTITY_INSERT [dbo].[AspNetUsers] on
delete AspNetUsers
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (1, 'cmccoughan0@businessinsider.com', 1, 'RyKwmzz', '', '717-946-7052', 1, 1, '10/9/2018', 1, 1, 'bfurse0@vimeo.com', '0', 1, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (2, 'edrieu1@sciencedirect.com', 2, 'ondlJ59y', '', '864-891-6918', 2, 2, '11/5/2018', 2, 2, 'gveck1@unicef.org', '0', 2, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (3, 'scousins2@usatoday.com', 3, '3PjG9gR', '', '410-210-2000', 3, 3, '12/28/2017', 3, 3, 'whedingham2@stumbleupon.com', '0', 3, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (4, 'lwarcup3@smugmug.com', 4, 'Oy1xB4CF', '', '948-322-4903', 4, 4, '3/24/2018', 4, 4, 'aaughtie3@jiathis.com', '1', 4, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (5, 'ntatershall4@sohu.com', 5, 'h4rYBEaqpM8', '', '448-455-3556', 5, 5, '1/5/2018', 5, 5, 'hgommes4@whitehouse.gov', '0', 5, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (6, 'jadelman5@cnbc.com', 6, 'wJrCpqV', '', '228-735-3511', 6, 6, '6/6/2018', 6, 6, 'ebaudy5@github.com', '1', 6, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (7, 'gstaves6@noaa.gov', 7, 'zhdaAu6', '', '888-391-4571', 7, 7, '2/22/2018', 7, 7, 'rscolts6@bigcartel.com', '0', 7, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (8, 'cfranzke7@furl.net', 8, 'gCTATvUUlR', '', '759-255-3102', 8, 8, '12/8/2017', 8, 8, 'smansour7@cpanel.net', '0', 8, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (9, 'sellum8@behance.net', 9, 'yDTHReUJT', '', '509-862-0161', 9, 9, '6/5/2018', 9, 9, 'gcastleton8@narod.ru', '1', 9, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (10, 'eirons9@hibu.com', 10, 'xXBJPBk4tXi', '', '167-905-0753', 10, 10, '9/11/2018', 10, 10, 'pdeferrari9@va.gov', '0', 10, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (11, 'cwettona@odnoklassniki.ru', 11, 'LExrvtIWdZT', '', '949-331-3655', 11, 11, '10/14/2018', 11, 11, 'aderilla@360.cn', '1', 11, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (12, 'lstoakesb@bravesites.com', 12, 'g71BUkfpxAR', '', '721-419-4381', 12, 12, '8/18/2018', 12, 12, 'wdumbellb@google.ru', '0', 12, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (13, 'orisomc@ocn.ne.jp', 13, 'jhGfuUOJQ', '', '272-744-2238', 13, 13, '4/28/2018', 13, 13, 'pfranksc@typepad.com', '1', 13, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (14, 'lwateridged@un.org', 14, 'nrrJ8nA8ySaN', '', '513-561-6082', 14, 14, '6/6/2018', 14, 14, 'lcafferyd@google.co.uk', '1', 14, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (15, 'seichmanne@bbc.co.uk', 15, '9wrW9sIE8Q8', '', '981-455-5481', 15, 15, '1/1/2018', 15, 15, 'awhilee@godaddy.com', '1', 15, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (16, 'ncrossgrovef@miitbeian.gov.cn', 16, 'EMxF4bDz', '', '868-531-1299', 16, 16, '4/9/2018', 16, 16, 'cmarlowf@globo.com', '0', 16, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (17, 'fskeermorg@cyberchimps.com', 17, 'GO35ptg', '', '477-239-3772', 17, 17, '1/31/2018', 17, 17, 'lbritiang@people.com.cn', '0', 17, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (18, 'kmouranth@histats.com', 18, 'CfAvhSDL6kKW', '', '773-685-0393', 18, 18, '6/3/2018', 18, 18, 'bdawidowskyh@google.it', '0', 18, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (19, 'pcasswelli@usatoday.com', 19, 'Y7xgVvB7cZF', '', '309-332-3309', 19, 19, '10/27/2018', 19, 19, 'mroxbroughi@pbs.org', '1', 19, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (20, 'ghariotj@cocolog-nifty.com', 20, '02fdJN', '', '493-562-1894', 20, 20, '6/18/2018', 20, 20, 'lshirdj@nsw.gov.au', '1', 20, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (21, 'pfianderk@qq.com', 21, 'ghibq4F', '', '484-636-5403', 21, 21, '3/4/2018', 21, 21, 'acorringhamk@nps.gov', '0', 21, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (22, 'kreggianil@meetup.com', 22, '8CHQCK', '', '828-588-7429', 22, 22, '9/30/2018', 22, 22, 'vocodihiel@economist.com', '1', 22, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (23, 'pmckleodm@blinklist.com', 23, 'ObUC0I5ZsI16', '', '766-250-2545', 23, 23, '5/5/2018', 23, 23, 'egoldsteinm@theguardian.com', '0', 23, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (24, 'kkuppern@ox.ac.uk', 24, 'hlWWqpSYouS', '', '257-278-7563', 24, 24, '7/20/2018', 24, 24, 'joshielsn@google.co.uk', '0', 24, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (25, 'gdunkleyo@xing.com', 25, 'ye0GAcyZ', '', '978-154-4907', 25, 25, '1/30/2018', 25, 25, 'rtracyo@netlog.com', '0', 25, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (26, 'cmclaughlinp@loc.gov', 26, 'xKfWlN', '', '325-862-5493', 26, 26, '8/5/2018', 26, 26, 'wcarbettp@seattletimes.com', '0', 26, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (27, 'cdeversonq@ox.ac.uk', 27, '8vKgzf3', '', '166-976-9256', 27, 27, '5/10/2018', 27, 27, 'rfilippovq@bigcartel.com', '1', 27, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (28, 'fcampanellir@google.com.au', 28, 'y8iAG0ngr', '', '837-492-0958', 28, 28, '10/31/2018', 28, 28, 'maffusor@dropbox.com', '0', 28, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (29, 'zauduss@surveymonkey.com', 29, '1wcyFl4Qhr', '', '585-319-1808', 29, 29, '8/7/2018', 29, 29, 'cmartynss@walmart.com', '0', 29, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (30, 'bhenaughant@upenn.edu', 30, 'DEh3dK', '', '445-949-3036', 30, 30, '2/16/2018', 30, 30, 'rkirtlandt@vinaora.com', '0', 30, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (31, 'sbassomu@technorati.com', 31, 'FMCvUXWxxXj2', '', '609-344-6675', 31, 31, '8/29/2018', 31, 31, 'hnealonu@nature.com', '1', 31, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (32, 'dhandrickv@soundcloud.com', 32, '4f4LbjqX', '', '756-529-9663', 32, 32, '5/26/2018', 32, 32, 'sstookesv@mtv.com', '0', 32, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (33, 'dkeeleyw@blogs.com', 33, 'IBuzCEEsLH1', '', '283-234-1229', 33, 33, '4/20/2018', 33, 33, 'jveschambesw@imdb.com', '1', 33, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (34, 'transcombx@yellowbook.com', 34, 'Qt9KaHY', '', '713-792-8992', 34, 34, '8/12/2018', 34, 34, 'jmiskimmonx@goo.ne.jp', '0', 34, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (35, 'gpitthamy@amazon.co.jp', 35, 'Qt09RmU7EPA', '', '308-711-2144', 35, 35, '4/8/2018', 35, 35, 'sleythleyy@nih.gov', '0', 35, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (36, 'wheggez@google.com.br', 36, 'F8CnZk', '', '779-364-1125', 36, 36, '2/26/2018', 36, 36, 'ljossumz@ft.com', '0', 36, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (37, 'mdebow10@forbes.com', 37, '5p482JTXk4', '', '573-664-6327', 37, 37, '10/1/2018', 37, 37, 'erawdales10@paginegialle.it', '1', 37, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (38, 'aparmenter11@google.pl', 38, 'WWgUr2Jo3ZJ', '', '968-485-0600', 38, 38, '8/10/2018', 38, 38, 'tlebarree11@nasa.gov', '0', 38, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (39, 'sbelward12@guardian.co.uk', 39, 'diT9byNz3', '', '655-895-4961', 39, 39, '12/27/2017', 39, 39, 'kfashion12@gnu.org', '1', 39, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (40, 'fbestman13@bloglovin.com', 40, 'ZVlbPrjgjT', '', '810-889-9743', 40, 40, '9/9/2018', 40, 40, 'jlabb13@cargocollective.com', '0', 40, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (41, 'sbaddiley14@phoca.cz', 41, 'xO6twKZ', '', '707-916-6112', 41, 41, '9/1/2018', 41, 41, 'erivel14@moonfruit.com', '0', 41, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (42, 'mbigmore15@stanford.edu', 42, 'nEeL3HYXnvq', '', '837-821-3833', 42, 42, '7/4/2018', 42, 42, 'diremonger15@clickbank.net', '0', 42, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (43, 'skrop16@quantcast.com', 43, 'wBozspu', '', '210-921-7261', 43, 43, '3/16/2018', 43, 43, 'nroyl16@ucsd.edu', '1', 43, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (44, 'kjorcke17@wikispaces.com', 44, 'Cl6qyj', '', '309-402-4908', 44, 44, '10/15/2018', 44, 44, 'glorrimer17@blog.com', '1', 44, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (45, 'lgrocott18@wikimedia.org', 45, 'wUtmhJ2T9p', '', '956-543-9889', 45, 45, '9/11/2018', 45, 45, 'jlowther18@chron.com', '0', 45, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (46, 'tscane19@google.com.br', 46, 'eqY6FQSj', '', '415-337-6993', 46, 46, '1/8/2018', 46, 46, 'spetric19@tripadvisor.com', '0', 46, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (47, 'fearwicker1a@nba.com', 47, 'JGJqsi6DxI', '', '370-563-0062', 47, 47, '1/12/2018', 47, 47, 'epfeuffer1a@youtube.com', '1', 47, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (48, 'sanwyl1b@hhs.gov', 48, 'IFOeMvjQKk', '', '150-908-3060', 48, 48, '7/15/2018', 48, 48, 'dbarthot1b@odnoklassniki.ru', '1', 48, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (49, 'lonion1c@pbs.org', 49, 'r6JKLXrX1D', '', '175-901-6764', 49, 49, '2/17/2018', 49, 49, 'gboutflour1c@typepad.com', '1', 49, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (50, 'fjestico1d@surveymonkey.com', 50, 'AaMSfsgU', '', '833-802-3727', 50, 50, '1/4/2018', 50, 50, 'bcastaignet1d@elegantthemes.com', '1', 50, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (51, 'sdangl1e@gizmodo.com', 51, '7wprmyw', '', '363-862-1115', 51, 51, '12/28/2017', 51, 51, 'swadeling1e@ameblo.jp', '0', 51, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (52, 'acoppard1f@japanpost.jp', 52, 'sntJ7vxyEvw', '', '280-585-6819', 52, 52, '2/27/2018', 52, 52, 'egillet1f@acquirethisname.com', '1', 52, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (53, 'hbrent1g@cloudflare.com', 53, 'S1eW6oAlcCP', '', '621-625-5434', 53, 53, '1/15/2018', 53, 53, 'allewellyn1g@goo.ne.jp', '1', 53, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (54, 'bfasson1h@reverbnation.com', 54, 'bv6t99h4N', '', '721-398-5661', 54, 54, '10/14/2018', 54, 54, 'ghalse1h@usnews.com', '0', 54, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (55, 'jlangfat1i@free.fr', 55, '45ZVinUx4AGi', '', '664-221-9196', 55, 55, '8/20/2018', 55, 55, 'mmcclaren1i@dailymotion.com', '0', 55, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (56, 'gsteen1j@stanford.edu', 56, '6ittoVxD8', '', '475-965-7544', 56, 56, '3/23/2018', 56, 56, 'yschild1j@privacy.gov.au', '1', 56, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (57, 'tkhomich1k@loc.gov', 57, 'TdGEWD', '', '883-430-8950', 57, 57, '3/3/2018', 57, 57, 'gkiljan1k@indiegogo.com', '1', 57, 'Administrator');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (58, 'mvanichkov1l@wsj.com', 58, 'TFzhgoX', '', '650-403-9924', 58, 58, '9/6/2018', 58, 58, 'gpaulig1l@icq.com', '0', 58, 'Client');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (59, 'obirdseye1m@addthis.com', 59, 't5HvroGz3JQy', '', '310-464-7436', 59, 59, '2/27/2018', 59, 59, 'vstpierre1m@jigsy.com', '0', 59, 'Ressource');
insert into AspNetUsers (Id, Email, EmailConfirmed, PasswordHash, SecurityStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEndDateUtc, LockoutEnabled, AccessFailedCount, UserName, typec, Rating, Discriminator) values (60, 'eblamire1n@furl.net', 60, 'K9pmwRbhajN', '', '344-285-4192', 60, 60, '6/6/2018', 60, 60, 'ideclerc1n@usda.gov', '1', 60, 'Administrator');
Insert INTO [dbo].[AspNetUsers] ([Id], [AccountType], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Type], [Category], [Name], [Photo], [typec], [Rating], [Seniority], [Status], [Name1], [IdProfile], [Specialty], [Discriminator], [JobRequest_IdRequest]) VALUES (420, NULL, N'riahi@furl.net', 1, N'K9pmwRbhajN', N'', N'344-285-4192', 1, 1, N'2018-06-06 00:00:00', 1, 60, N'ideclerc1n@usda.gov', NULL, NULL, NULL, NULL, 0, 60, NULL, NULL, NULL, NULL, NULL, N'Ressource', NULL)
Insert INTO [dbo].[AspNetUsers] ([Id], [AccountType], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Type], [Category], [Name], [Photo], [typec], [Rating], [Seniority], [Status], [Name1], [IdProfile], [Specialty], [Discriminator], [JobRequest_IdRequest]) VALUES (70, NULL, N'riahi@chirl.net', 1, N'K9pmwRbhajN', N'', N'344-285-4192', 1, 1, N'2018-06-06 00:00:00', 1, 60, N'ifjg@usdfa.gov', NULL, NULL, NULL, NULL, 1, 60, NULL, NULL, NULL, NULL, NULL, N'Ressource', NULL)
Insert INTO [dbo].[AspNetUsers] ([Id], [AccountType], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Type], [Category], [Name], [Photo], [typec], [Rating], [Seniority], [Status], [Name1], [IdProfile], [Specialty], [Discriminator], [JobRequest_IdRequest]) VALUES (90, NULL, N'riahi@sars.net', 1, N'K9pmwRbhajN', N'', N'344-285-4192', 1, 1, N'2018-06-06 00:00:00', 1, 60, N'ilerc1n@usffda.gov', NULL, NULL, NULL, NULL, 0, 60, NULL, NULL, NULL, NULL, NULL, N'Ressource', NULL)
Insert INTO [dbo].[AspNetUsers] ([Id], [AccountType], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Type], [Category], [Name], [Photo], [typec], [Rating], [Seniority], [Status], [Name1], [IdProfile], [Specialty], [Discriminator], [JobRequest_IdRequest]) VALUES (75, NULL, N'jihji@furl.net', 1, N'K9pmwRbhajN', N'', N'344-285-4192', 1, 1, N'2018-06-06 00:00:00', 1, 60, N'rc1n@ua.gov', NULL, NULL, NULL, NULL, 1, 60, NULL, NULL, NULL, NULL, NULL, N'Ressource', NULL)
Insert INTO [dbo].[AspNetUsers] ([Id], [AccountType], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Type], [Category], [Name], [Photo], [typec], [Rating], [Seniority], [Status], [Name1], [IdProfile], [Specialty], [Discriminator], [JobRequest_IdRequest]) VALUES (420, NULL, N'riahjdhfi@furl.net', 1, N'K9pmwRbhajN', N'', N'344-285-4192', 1, 1, N'2018-06-06 00:00:00', 1, 60, N'i1n@ufda.gov', NULL, NULL, NULL, NULL, 0, 60, NULL, NULL, NULL, NULL, NULL, N'Ressource', NULL)
Insert INTO [dbo].[AspNetUsers] ([Id], [AccountType], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Type], [Category], [Name], [Photo], [typec], [Rating], [Seniority], [Status], [Name1], [IdProfile], [Specialty], [Discriminator], [JobRequest_IdRequest]) VALUES (73, NULL, N'rihidki@chirl.net', 1, N'K9pmwRbhajN', N'', N'344-285-4192', 1, 1, N'2018-06-06 00:00:00', 1, 60, N'jic1n@usj.gov', NULL, NULL, NULL, NULL, 1, 60, NULL, NULL, NULL, NULL, NULL, N'Ressource', NULL)
Insert INTO [dbo].[AspNetUsers] ([Id], [AccountType], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Type], [Category], [Name], [Photo], [typec], [Rating], [Seniority], [Status], [Name1], [IdProfile], [Specialty], [Discriminator], [JobRequest_IdRequest]) VALUES (91, NULL, N'saber@sars.net', 1, N'K9pmwRbhajN', N'', N'344-285-4192', 1, 1, N'2018-06-06 00:00:00', 1, 60, N'hjh1n@usrfrr.gov', NULL, NULL, NULL, NULL, 1, 60, NULL, NULL, NULL, NULL, NULL, N'Ressource', NULL)
Insert INTO [dbo].[AspNetUsers] ([Id], [AccountType], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Type], [Category], [Name], [Photo], [typec], [Rating], [Seniority], [Status], [Name1], [IdProfile], [Specialty], [Discriminator], [JobRequest_IdRequest]) VALUES (68, NULL, N'jihji@furl.net', 1, N'K9pmwRbhajN', N'', N'344-285-4192', 1, 1, N'2018-06-06 00:00:00', 1, 60, N'ieyygn@usd.gov', NULL, NULL, NULL, NULL, 1, 60, NULL, NULL, NULL, NULL, NULL, N'Ressource', NULL)

SET IDENTITY_INSERT [dbo].[AspNetUsers] off

--Select Id from AspNetUsers where Discriminator = 'Ressource' 
